services:
  mongo1:
    image: mongo:8.3.1
    container_name: mongo1
    hostname: mongo1
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "30001"]
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - "30001:30001"
    networks:
      - net

  mongo2:
    image: mongo:8.3.1
    container_name: mongo2
    hostname: mongo2
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "30002"]
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - "30002:30002"
    networks:
      - net

  mongo3:
    image: mongo:8.3.1
    container_name: mongo3
    hostname: mongo3
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "30003"]
    volumes:
      - ./data/mongo-3:/data/db
    ports:
      - "30003:30003"
    networks:
      - net

  mongo-init:
    image: mongo:8.3.1
    container_name: mongo-init
    restart: "no"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint:
      - bash
      - -lc
      - |
        echo "Waiting for Mongo nodes..."
        until mongosh --host mongo1 --port 30001 --eval "db.runCommand({ ping: 1 })" >/dev/null 2>&1; do sleep 2; done
        until mongosh --host mongo2 --port 30002 --eval "db.runCommand({ ping: 1 })" >/dev/null 2>&1; do sleep 2; done
        until mongosh --host mongo3 --port 30003 --eval "db.runCommand({ ping: 1 })" >/dev/null 2>&1; do sleep 2; done

        echo "Initializing replica set if needed..."
        mongosh --host mongo1 --port 30001 --eval '
          try {
            rs.status();
            print("Replica set already initialized");
          } catch (e) {
            rs.initiate({
              _id: "rs0",
              members: [
                { _id: 0, host: "mongo1:30001" },
                { _id: 1, host: "mongo2:30002" },
                { _id: 2, host: "mongo3:30003" }
              ]
            });
          }
        '

        echo "Waiting for replica set connection..."
        until mongosh "mongodb://mongo1:30001,mongo2:30002,mongo3:30003/?replicaSet=rs0" \
          --eval "db.adminCommand({ ping: 1 })" >/dev/null 2>&1; do
          sleep 2
        done

        echo "Replica set ready"
    networks:
      - net

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: on-failure
    depends_on:
      mongo-init:
        condition: service_completed_successfully

    ports:
      - "8080:8080"
    environment:
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - net

networks:
  net:
    driver: bridge