server:
  port: ${APP_PORT}

spring:
  mongodb:
    host: ${MONGO1_HOST},${MONGO2_HOST},${MONGO3_HOST}
    port: ${MONGO_PORT}
    replica-set-name: ${RS_NAME}
    database: ${MONGO_DB_NAME}
  data:
    mongodb:
      auto-index-creation: false   # Indexes are managed by Liquibase changesets

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  codec:
    max-in-memory-size: 5MB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token:
    prefix: "Bearer "
  access-token:
    expiration-time-ms: 300000
  refresh-token:
    expiration-time-ms: 28800000
    access-token-key: AccessTokenKey

springdoc:
  api-docs:
    groups:
      enabled: true
  packages-to-scan: com.rzodeczko
  swagger-ui:
    path: /docs
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs

app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin1234}

management:
  endpoints:
    web:
      exposure:
        include: health