server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://mongo1:30001,mongo2:30002,mongo3:30003/?replicaSet=rs0
      database: cinema_db

mail:
  host: smtp.gmail.com
  username: firelight.code@gmail.com
  password: rxzbacwpboqvjllq
  port: 587
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

adminpassword: password@1


jwt:
  token:
    prefix: Bearer
  access-token:
    expiration-time-ms: 300000
  refresh-token:
    expiration-time-ms: 28800000
    access-token-key: AccessTokenKey

springdoc:
  api-docs:
    groups:
      enabled: true
  packages-to-scan: com.app
  swagger-ui:
    path: /docs

change-logs-scan-package: com.app.infrastructure.mongo.initscripts
adminusername: admin123
