server:
  port: 8080

spring:
  mongodb:
    uri: mongodb://mongo1:${MONGO1_PORT:30001},mongo2:${MONGO2_PORT:30002},mongo3:${MONGO3_PORT:30003}/cinema_db?replicaSet=rs0

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  codec:
    max-in-memory-size: 5MB

mongock:
  migration-scan-package: com.app.infrastructure.mongo.initscripts

jwt:
  secret-key: ${JWT_SECRET_KEY}
  token:
    prefix: Bearer
  access-token:
    expiration-time-ms: 300000
  refresh-token:
    expiration-time-ms: 28800000
    access-token-key: AccessTokenKey

springdoc:
  api-docs:
    groups:
      enabled: true
  packages-to-scan: com.rzodeczko
  swagger-ui:
    path: /docs
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  group-configs:


adminusername: ${ADMIN_USERNAME:admin}
adminpassword: ${ADMIN_PASSWORD:admin}


management:
  endpoints:
    web:
      exposure:
        include: health
